#!/bin/zsh

if [ -z "$1" ]; then
	echo "Please provide the name of the function to deploy"
	exit 1
fi

function_name="$1"

case $function_name in
  mailbox_change|refresh_mailbox_sub)
    trigger="PUBSUB"
    ;;
  sync_gmail|watch_gmail_mailbox|create_user)
    trigger="HTTP"
    ;;
  *)
    echo "Invalid function_name: $function_name"
    exit 1
    ;;
esac

env_yaml=".env.yaml"
env=".env.prod"

# Check if env_yaml exists
if [ -f "$env_yaml" ]; then
    # If the file exists, truncate/empty it
    rm $env_yaml
fi

touch $env_yaml

# Read each line from .env
while IFS='=' read -r key value
do
  # Write the key value pair to .env.yaml
  echo "$key: '$value'" >> $env_yaml
done < $env

source ../.env

if [ "$trigger" = "HTTP" ]; then
    gcloud functions deploy $function_name \
		--gen2 \
		--configuration=$CLOUD_SDK_CONFIG \
		--project=$GOOGLE_PROJECT_ID \
		--env-vars-file=.env.yaml \
		--runtime=python311 \
		--region=$CLOUD_REGION \
		--source=. \
		--entry-point=$function_name \
	    --trigger-http
elif [ "$trigger" = "PUBSUB" ]; then
	gcloud functions deploy $function_name \
		--gen2 \
		--configuration=$CLOUD_SDK_CONFIG \
		--project=$GOOGLE_PROJECT_ID \
		--env-vars-file=.env.yaml \
		--runtime=python311 \
		--region=$CLOUD_REGION \
		--source=. \
		--entry-point=$function_name \
	    --trigger-topic=$GOOGLE_PUBSUB_TOPIC
fi
	